version: 0.0.1
services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postgres@db/postgres
  db:
    image: "postgres:15"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
