name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: Swatinem/rust-cache@v2.5.1
        with:
          workspaces: api -> target
          shared-key: rust-dev
      - name: Build
        working-directory: api
        run: cargo build --verbose
  unit-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: Swatinem/rust-cache@v2.5.1
        with:
          workspaces: api -> target
          shared-key: rust-dev
      - name: Unit Tests
        working-directory: api
        run: cargo test --verbose
